// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'item-section-s1-head-text'
  | 'item-section-s1-sidenav-tooltip'
  | 'pref-autoTranslate'
  | 'pref-autoTranslateMinChars'
  | 'pref-codexAuthPath'
  | 'pref-grokApiKey'
  | 'pref-grokAuthPath'
  | 'pref-grokBaseUrl'
  | 'pref-help'
  | 'pref-model'
  | 'pref-provider'
  | 'pref-targetLang'
  | 'pref-test'
  | 'pref-title'
  | 'prefs-title'
  | 'startup-begin'
  | 'startup-finish';
