// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "provider": string;
      "model": string;
      "grokApiKey": string;
      "grokBaseUrl": string;
      "grokAuthPath": string;
      "codexAuthPath": string;
      "targetLang": string;
      "autoTranslateOnSelect": boolean;
      "autoTranslateMinChars": number;
      "translateResultW": number;
      "translateResultH": number;
      "reasoningEffort": string;
      "translateProvider": string;
      "translateModel": string;
      "translateBaseUrl": string;
      "translateReasoning": string;
      "explainProvider": string;
      "explainModel": string;
      "explainBaseUrl": string;
      "explainReasoning": string;
      "chatProvider": string;
      "chatModel": string;
      "chatBaseUrl": string;
      "chatReasoning": string;
      "figureProvider": string;
      "figureModel": string;
      "figureBaseUrl": string;
      "figureReasoning": string;
      "ragEnabled": boolean;
      "ragRetrievalMode": string;
      "ragTopK": number;
      "ragStuffTokenLimit": number;
      "embeddingProvider": string;
      "embeddingBaseUrl": string;
      "embeddingApiKey": string;
      "embeddingModel": string;
    };
  }
}
